# Regression and Classification

*Part of this section is drafted based on Dr. Mark Hoffman's previous SOC 10 lab notes.*

This week our tutorial will cover social network analysis. Social network analysis focuses on patterns of relations between actors and is a key approach to study issues like homopohily and social diffusion. 

## Understanding network data structures in R

One simple way to represent a graph is to list the edges, which we will refer to as an edge list. For each edge, we just list who that edge is incident on. Edge lists are therefore two column matrices (or dataframe in the language of R) that directly tell the computer which actors are tied for each edge. In a directed graph, the actors in column A are the sources of edges, and the actors in Column B receive the tie. In an undirected graph, order doesn’t matter.

Let me use a real social network data as a guiding example for the tutorial. This network is a network of scene coappearances of characters in Victor Hugo's novel "Les Miserables." Edge weights denote the number of such occurrences. The data source is D. E. Knuth, "The Stanford GraphBase: A Platform for Combinatorial Computing." Addison-Wesley, Reading, MA (1993).

I converted the raw data format to make it easy for use in R. Let's load the "lesmis_edges.csv" first, which is the edge list file. 

```r
edges  <- read.csv("lesmis_edges.csv")
```

Let's take a look at this dataframe using function head():

```r
head(edges)
```
```r
  source target weight
1      1      2      1
2      1      3      8
3      1      4     10
4      1      5      1
5      1      6      1
6      1      7      1
```
We can see that there are three columns. The first two columns define the source and the target of the connection. The numerical values in these two columns represent different network nodes (here they represent individual characters in the novel). They do not have to be numerical IDs and we could put in actual character names instead, which is more readable but take up more storage space on our disk. 

In the case of co-appearence, linkages are not directional. Thus, each pair of node IDs only appear once. For a directed network, each pair of nodes could appear twice (e.g., 1 -- > 2 vs. 2 -- > 1. In the first case, 1 is the sending node and in the second case, 2 is the sending node).

For the edgelist dataframe, we only report node pairs that have links. Thus the third column, which represents the intensity of the connection (i.e., edge weight), is never zero. The "weight" column could have varied values if the network is weighted. The Les Miserables network is weighted that weights represent the number of co-occurence. For some networks, egdes are not weighted (i.e., weight column = 1 for all rows). For such unweighted networks, we could omit the "weight" column. 








