<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Week 7 Machine Learning (Supervised Learning) | Stanford Spring 2025 Intro to Computational Social Science</title>
  <meta name="description" content="Week 7 Machine Learning (Supervised Learning) | Stanford Spring 2025 Intro to Computational Social Science" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Week 7 Machine Learning (Supervised Learning) | Stanford Spring 2025 Intro to Computational Social Science" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 7 Machine Learning (Supervised Learning) | Stanford Spring 2025 Intro to Computational Social Science" />
  
  
  

<meta name="author" content="Yuze Sui" />


<meta name="date" content="2025-03-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="text-analysis.html"/>
<link rel="next" href="large-language-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intro_Comp_Social_Science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="1" data-path="intro-to-r.html"><a href="intro-to-r.html"><i class="fa fa-check"></i><b>1</b> Intro to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro-to-r.html"><a href="intro-to-r.html#r-basics"><i class="fa fa-check"></i><b>1.1</b> R Basics</a></li>
<li class="chapter" data-level="1.2" data-path="intro-to-r.html"><a href="intro-to-r.html#vectors"><i class="fa fa-check"></i><b>1.2</b> Vectors</a></li>
<li class="chapter" data-level="1.3" data-path="intro-to-r.html"><a href="intro-to-r.html#loading-packages"><i class="fa fa-check"></i><b>1.3</b> Loading Packages</a></li>
<li class="chapter" data-level="1.4" data-path="intro-to-r.html"><a href="intro-to-r.html#exploring-and-visualizing-data"><i class="fa fa-check"></i><b>1.4</b> Exploring and Visualizing Data</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="surveys-and-survey-experiments-with-qualtrics.html"><a href="surveys-and-survey-experiments-with-qualtrics.html"><i class="fa fa-check"></i><b>2</b> Surveys and Survey Experiments with Qualtrics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="surveys-and-survey-experiments-with-qualtrics.html"><a href="surveys-and-survey-experiments-with-qualtrics.html#overview"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="surveys-and-survey-experiments-with-qualtrics.html"><a href="surveys-and-survey-experiments-with-qualtrics.html#creating-a-qualtrics-account"><i class="fa fa-check"></i><b>2.2</b> Creating a Qualtrics account</a></li>
<li class="chapter" data-level="2.3" data-path="surveys-and-survey-experiments-with-qualtrics.html"><a href="surveys-and-survey-experiments-with-qualtrics.html#survey-options"><i class="fa fa-check"></i><b>2.3</b> Survey options</a></li>
<li class="chapter" data-level="2.4" data-path="surveys-and-survey-experiments-with-qualtrics.html"><a href="surveys-and-survey-experiments-with-qualtrics.html#a-quick-survey-experiment"><i class="fa fa-check"></i><b>2.4</b> A quick survey experiment</a></li>
<li class="chapter" data-level="2.5" data-path="surveys-and-survey-experiments-with-qualtrics.html"><a href="surveys-and-survey-experiments-with-qualtrics.html#publish-it"><i class="fa fa-check"></i><b>2.5</b> Publish it!</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression-and-classification.html"><a href="regression-and-classification.html"><i class="fa fa-check"></i><b>3</b> Regression and Classification</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regression-and-classification.html"><a href="regression-and-classification.html#linear-regression"><i class="fa fa-check"></i><b>3.1</b> Linear Regression</a></li>
<li class="chapter" data-level="3.2" data-path="regression-and-classification.html"><a href="regression-and-classification.html#how-linear-regression-works"><i class="fa fa-check"></i><b>3.2</b> How linear regression works</a></li>
<li class="chapter" data-level="3.3" data-path="regression-and-classification.html"><a href="regression-and-classification.html#linear-regression-using-the-lm-function"><i class="fa fa-check"></i><b>3.3</b> Linear regression using the lm function</a></li>
<li class="chapter" data-level="3.4" data-path="regression-and-classification.html"><a href="regression-and-classification.html#multiple-regression"><i class="fa fa-check"></i><b>3.4</b> Multiple Regression</a></li>
<li class="chapter" data-level="3.5" data-path="regression-and-classification.html"><a href="regression-and-classification.html#linear-regression-prediction"><i class="fa fa-check"></i><b>3.5</b> Linear Regression Prediction</a></li>
<li class="chapter" data-level="3.6" data-path="regression-and-classification.html"><a href="regression-and-classification.html#classification-logistic-regression"><i class="fa fa-check"></i><b>3.6</b> Classification (Logistic Regression)</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="social-network-analysis.html"><a href="social-network-analysis.html"><i class="fa fa-check"></i><b>4</b> Social Network Analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="social-network-analysis.html"><a href="social-network-analysis.html#understanding-network-data-structures-in-r"><i class="fa fa-check"></i><b>4.1</b> Understanding network data structures in R</a></li>
<li class="chapter" data-level="4.2" data-path="social-network-analysis.html"><a href="social-network-analysis.html#visualizing-network-data-in-r"><i class="fa fa-check"></i><b>4.2</b> Visualizing network data in R</a></li>
<li class="chapter" data-level="4.3" data-path="social-network-analysis.html"><a href="social-network-analysis.html#key-network-measures"><i class="fa fa-check"></i><b>4.3</b> Key network measures</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="social-network-analysis.html"><a href="social-network-analysis.html#degree-how-many-friends-do-i-have"><i class="fa fa-check"></i><b>4.3.1</b> Degree (“How many friends do I have?”)</a></li>
<li class="chapter" data-level="4.3.2" data-path="social-network-analysis.html"><a href="social-network-analysis.html#weighted-degree-strength"><i class="fa fa-check"></i><b>4.3.2</b> Weighted degree (strength)</a></li>
<li class="chapter" data-level="4.3.3" data-path="social-network-analysis.html"><a href="social-network-analysis.html#global-clustering-coefficient-gcc"><i class="fa fa-check"></i><b>4.3.3</b> Global Clustering Coefficient (GCC)</a></li>
<li class="chapter" data-level="4.3.4" data-path="social-network-analysis.html"><a href="social-network-analysis.html#average-path-length-apl"><i class="fa fa-check"></i><b>4.3.4</b> Average path length (APL)</a></li>
<li class="chapter" data-level="4.3.5" data-path="social-network-analysis.html"><a href="social-network-analysis.html#assortativity"><i class="fa fa-check"></i><b>4.3.5</b> Assortativity</a></li>
<li class="chapter" data-level="4.3.6" data-path="social-network-analysis.html"><a href="social-network-analysis.html#betweenness-centrality"><i class="fa fa-check"></i><b>4.3.6</b> Betweenness centrality</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="social-network-analysis.html"><a href="social-network-analysis.html#visualizing-key-measures"><i class="fa fa-check"></i><b>4.4</b> Visualizing Key Measures</a></li>
<li class="chapter" data-level="4.5" data-path="social-network-analysis.html"><a href="social-network-analysis.html#benchmark-our-empirical-network"><i class="fa fa-check"></i><b>4.5</b> Benchmark our empirical network</a></li>
<li class="chapter" data-level="4.6" data-path="social-network-analysis.html"><a href="social-network-analysis.html#find-local-clusterscommunities"><i class="fa fa-check"></i><b>4.6</b> Find local clusters/communities</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="social-network-analysis.html"><a href="social-network-analysis.html#other-resources"><i class="fa fa-check"></i><b>4.6.1</b> Other Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="collecting-data-online.html"><a href="collecting-data-online.html"><i class="fa fa-check"></i><b>5</b> Collecting Data Online</a>
<ul>
<li class="chapter" data-level="5.1" data-path="collecting-data-online.html"><a href="collecting-data-online.html#scraping-the-web"><i class="fa fa-check"></i><b>5.1</b> Scraping the web</a></li>
<li class="chapter" data-level="5.2" data-path="collecting-data-online.html"><a href="collecting-data-online.html#google-news-api"><i class="fa fa-check"></i><b>5.2</b> Google News API</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="collecting-data-online.html"><a href="collecting-data-online.html#prerequistes"><i class="fa fa-check"></i><b>5.2.1</b> Prerequistes</a></li>
<li class="chapter" data-level="5.2.2" data-path="collecting-data-online.html"><a href="collecting-data-online.html#get-started"><i class="fa fa-check"></i><b>5.2.2</b> Get started</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="text-analysis.html"><a href="text-analysis.html"><i class="fa fa-check"></i><b>6</b> Text Analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="text-analysis.html"><a href="text-analysis.html#sentiment-analysis"><i class="fa fa-check"></i><b>6.1</b> Sentiment Analysis</a></li>
<li class="chapter" data-level="6.2" data-path="text-analysis.html"><a href="text-analysis.html#topic-modeling"><i class="fa fa-check"></i><b>6.2</b> Topic Modeling</a></li>
<li class="chapter" data-level="6.3" data-path="text-analysis.html"><a href="text-analysis.html#word-embeddings"><i class="fa fa-check"></i><b>6.3</b> Word Embeddings</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="machine-learning-supervised-learning.html"><a href="machine-learning-supervised-learning.html"><i class="fa fa-check"></i><b>7</b> Machine Learning (Supervised Learning)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="machine-learning-supervised-learning.html"><a href="machine-learning-supervised-learning.html#training-vs.-test-data-why-split"><i class="fa fa-check"></i><b>7.1</b> Training vs. Test Data: Why Split?</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="machine-learning-supervised-learning.html"><a href="machine-learning-supervised-learning.html#splitting-the-gss-2018-data"><i class="fa fa-check"></i><b>7.1.1</b> Splitting the GSS 2018 Data</a></li>
<li class="chapter" data-level="7.1.2" data-path="machine-learning-supervised-learning.html"><a href="machine-learning-supervised-learning.html#linear-regression-with-training-and-test-data"><i class="fa fa-check"></i><b>7.1.2</b> Linear Regression with Training and Test Data</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="machine-learning-supervised-learning.html"><a href="machine-learning-supervised-learning.html#decision-trees-for-regression"><i class="fa fa-check"></i><b>7.2</b> Decision Trees for Regression</a></li>
<li class="chapter" data-level="7.3" data-path="machine-learning-supervised-learning.html"><a href="machine-learning-supervised-learning.html#random-forests"><i class="fa fa-check"></i><b>7.3</b> Random Forests</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="large-language-models.html"><a href="large-language-models.html"><i class="fa fa-check"></i><b>8</b> Large Language Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="large-language-models.html"><a href="large-language-models.html#tidychatmodels-package"><i class="fa fa-check"></i><b>8.1</b> tidychatmodels Package</a></li>
<li class="chapter" data-level="8.2" data-path="large-language-models.html"><a href="large-language-models.html#llm-as-synthetic-respondents-for-social-survey-set-up"><i class="fa fa-check"></i><b>8.2</b> LLM as “Synthetic Respondents” for Social Survey: Set-up</a></li>
<li class="chapter" data-level="8.3" data-path="large-language-models.html"><a href="large-language-models.html#llm-as-synthetic-respondents-for-social-survey-query"><i class="fa fa-check"></i><b>8.3</b> LLM as “Synthetic Respondents” for Social Survey: Query</a></li>
<li class="chapter" data-level="8.4" data-path="large-language-models.html"><a href="large-language-models.html#other-use-cases-of-llm-apis-in-computatinal-social-science"><i class="fa fa-check"></i><b>8.4</b> Other Use Cases of LLM APIs in Computatinal Social Science</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stanford Spring 2025 Intro to Computational Social Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="machine-learning-supervised-learning" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Week 7</span> Machine Learning (Supervised Learning)<a href="machine-learning-supervised-learning.html#machine-learning-supervised-learning" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In previous weeks, we fit linear regressions and logistic regression using all available data. That is the conventional practice for explanatory studies but not for predictive studies (i.e., Machine Learning). Here, we introduce the practice of splitting data into training and test sets, and demonstrate why this is crucial for evaluating a model’s performance on new data. We will use the 2018 General Social Survey (GSS 2018) data and the same variables from prior labs (e.g., age, education, sex, and income) to build and compare three types of models:</p>
<p>A standard linear regression (as a baseline).
A decision tree regression model.
A random forest regression model.</p>
<p>We’ll fit each model on a training subset of the GSS data, evaluate their performance on both training and test sets, and compare their predictive accuracy using metrics like the Root Mean Squared Error (RMSE). Throughout, we will use the tidyverse and tidymodels frameworks for a consistent, tidy approach to modeling.</p>
<div id="training-vs.-test-data-why-split" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Training vs. Test Data: Why Split?<a href="machine-learning-supervised-learning.html#training-vs.-test-data-why-split" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When developing a predictive model, our goal is not just to describe the patterns in the training data but to make accurate predictions on new, unseen data. If we evaluate a model on the same data used for training, we risk being overly optimistic about its performance – the model may simply be memorizing noise or idiosyncrasies in that dataset, a phenomenon known as overfitting. By setting aside a portion of data as a test set (also called a hold-out set), we obtain an honest assessment of how the model might perform on future data. Key idea: We will split the GSS 2018 data into a training set (to fit the models) and a test set (to evaluate them). For example, we might use 80% of the data for training and reserve 20% for testing. The test set will act as new data that the model has not seen during training, allowing us to check how well the model generalizes. Let’s apply this concept using a linear regression model as an example. We’ll predict real household income (realinc) using respondents’ age, education (educ years), and sex – the same variables we explored in earlier regression labs. We will:</p>
<ol style="list-style-type: decimal">
<li>Split the GSS 2018 data into training and test sets.</li>
<li>Fit a linear regression on the training set.</li>
<li>Evaluate the model’s performance on both the training set and the test set, comparing metrics to see the difference.</li>
</ol>
<div id="splitting-the-gss-2018-data" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Splitting the GSS 2018 Data<a href="machine-learning-supervised-learning.html#splitting-the-gss-2018-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use initial_split() from the rsample package (part of tidymodels) to randomly split the data. Below, we split 80% of the GSS data into gss_train and 20% into gss_test. We set a random seed for reproducibility so everyone gets the same split:</p>
<pre><code>library(tidyverse)
library(tidymodels)
library(haven)
set.seed(123)  # for reproducibility of the random split
gss &lt;- read_dta(&quot;GSS2018.dta&quot;)

# Clean the variables
gss &lt;- gss %&gt;%                                             
  transmute(
    realinc = as.numeric(realinc),
    age     = as.numeric(age),
    educ    = as.numeric(educ),
    sex     = as_factor(sex)      # labelled  -&gt; factor
  ) %&gt;% 
  drop_na()      
  
# Create an 80/20 train-test split
gss_split &lt;- initial_split(gss, prop = 0.8)
gss_train &lt;- training(gss_split)
gss_test  &lt;- testing(gss_split)</code></pre>
<p>We can verify the split:</p>
<pre><code># Verify the split sizes
nrow(gss_train)
nrow(gss_test)</code></pre>
<pre><code>## [1] 1878
## [1] 470</code></pre>
<p>We have 2,348 observations in GSS 2018 (as seen in Week 1’s exploration), so the training set has 1,878 rows and the test set 470 rows (approximately 80/20 split). Now, we’ll build a linear regression model using the training data.</p>
</div>
<div id="linear-regression-with-training-and-test-data" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Linear Regression with Training and Test Data<a href="machine-learning-supervised-learning.html#linear-regression-with-training-and-test-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, we define a linear regression model specification using tidymodels’ parsnip package. We then fit this model to the training data, predicting realinc (real income) from age, educ, and sex. Finally, we evaluate the model’s performance on both training and test sets.</p>
<pre><code># Define a linear regression model specification
lin_mod &lt;- linear_reg() %&gt;% 
  set_engine(&quot;lm&quot;) %&gt;%            # use R&#39;s linear model engine
  set_mode(&quot;regression&quot;)          # this is a regression (predicting numeric outcome)

# Fit the model on the training data
lin_fit &lt;- lin_mod %&gt;% fit(realinc ~ age + educ + sex, data = gss_train)</code></pre>
<p>The model lin_fit now contains the linear regression results (coefficients, etc.) trained on gss_train. We can check how well this model fits the training data versus how well it predicts the test data. We’ll use the following metric:</p>
<p>RMSE (Root Mean Squared Error): the square root of the average squared error. This is in the same units as the outcome (income in dollars) – lower RMSE means better prediction.</p>
<p>Using the yardstick package (loaded via tidymodels), we can easily compute the metric. We’ll generate predictions on both the training set and test set, then calculate RMSE for each:</p>
<pre><code># Evaluate performance on the training data
lin_train_preds &lt;- predict(lin_fit, gss_train) %&gt;% 
  bind_cols(gss_train)          # bind predictions with true values
rmse(lin_train_preds, truth = realinc, estimate = .pred)</code></pre>
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    binary        28930.</code></pre>
<pre><code># Evaluate performance on the test data
lin_test_preds &lt;- predict(lin_fit, gss_test) %&gt;% 
  bind_cols(gss_test)
rmse(lin_test_preds, truth = realinc, estimate = .pred)</code></pre>
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    binary        28140.</code></pre>
<p>Interpretation: On the training data, our linear model has an RMSE of about 28,930, meaning on average the model’s predictions deviate from actual incomes by around $28k. On the test data, the RMSE is about 28140. These are very close to the training values (in fact, the test RMSE is slightly lower in this instance, which can happen by chance or if the model is slightly underfitting).</p>
<p>The key point is that the model’s performance on new data is in the same ballpark as on the training data, suggesting that our linear model did not severely overfit. This makes sense – a linear regression with three predictors is a relatively simple model (low variance), so it generalizes reasonably well.</p>
<p>Now that we understand training vs. test evaluation with a familiar model, let’s introduce more flexible machine learning models – decision trees and random forests – and see how they perform on the same task.</p>
</div>
</div>
<div id="decision-trees-for-regression" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Decision Trees for Regression<a href="machine-learning-supervised-learning.html#decision-trees-for-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Decision trees are intuitive, rule-based models that predict an outcome by learning a hierarchy of if-else rules from the data. For regression (continuous outcomes), a decision tree repeatedly splits the data into subsets based on predictor variables’ values, aiming to create groups that are as homogeneous as possible in the outcome. The result is a tree-like model where each leaf node yields a predicted value (typically the mean outcome of training cases in that leaf).</p>
<p>Why use trees? They can automatically capture non-linear relationships and interactions between predictors. For example, a tree could learn that income increases with education unless the person is above a certain age (retirement age), in which case income might drop – a pattern that a single linear model might miss. Trees are also easy to interpret (we can visualize the splits).</p>
<p>Downside: Decision trees are prone to overfitting if grown too deep. A fully grown tree can memorize the training data (yielding very low training error) but perform poorly on new data. We usually need to prune the tree or set limits on its depth/leaves to avoid overfitting. Let’s fit a decision tree on the same training data (gss_train) to predict realinc. We will use tidymodels again, with the rpart engine (which implements the CART algorithm for decision trees):</p>
<pre><code># Define a decision tree model specification for regression
tree_mod &lt;- decision_tree() %&gt;% 
  set_engine(&quot;rpart&quot;) %&gt;%        # CART algorithm implementation
  set_mode(&quot;regression&quot;)

# Fit the decision tree on the training data
tree_fit &lt;- tree_mod %&gt;% fit(realinc ~ age + educ + sex, data = gss_train)</code></pre>
<p>Now we have a trained decision tree model tree_fit. We’ll evaluate its RMSE on both training and test sets, just as we did for the linear model:</p>
<pre><code># Performance on training data
tree_train_preds &lt;- predict(tree_fit, gss_train) %&gt;% bind_cols(gss_train)
rmse(tree_train_preds, truth = realinc, estimate = .pred)</code></pre>
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard      27990.</code></pre>
<pre><code># Performance on test data
tree_test_preds &lt;- predict(tree_fit, gss_test) %&gt;% bind_cols(gss_test)
rmse(tree_test_preds, truth = realinc, estimate = .pred)</code></pre>
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard      26861.</code></pre>
<p>Interpretation: The decision tree’s training RMSE is lower than the linear model’s. This indicates the tree fit the training data more closely. Same for test set.</p>
<p>We can also evaluate predictor importance</p>
<pre><code># If vip isn&#39;t installed yet:
# install.packages(&quot;vip&quot;)

library(vip)
library(ggplot2)

# --- Compute and plot importance ---
vip::vip(tree_fit$fit,           # underlying rpart object
         num_features = 20) +    # show up to 20 predictors (adjust as needed)
  ggtitle(&quot;Decision tree – variable importance&quot;)</code></pre>
</div>
<div id="random-forests" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Random Forests<a href="machine-learning-supervised-learning.html#random-forests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Random forests offer one powerful solution. A random forest is essentially an ensemble of many decision trees. The idea is to build a large number of trees (e.g., 100 or 500), each on a slightly different random subset of the data and predictors, and then average their predictions. Key characteristics of random forests:</p>
<p>Each tree in the forest is trained on a bootstrapped sample of the training data (random sampling with replacement), and at each split, the tree considers a random subset of predictors (this is the “random” part of random forests).</p>
<p>Because each tree sees a slightly different view of the data, their errors are not perfectly correlated. Averaging many trees tends to cancel out noise and reduce overfitting, while capturing complex patterns.</p>
<p>Random forests usually don’t require much manual tuning of tree depth – the ensemble approach and averaging naturally controls variance. They often achieve better test performance than a single deep tree, at the cost of losing some interpretability (it’s no longer a single neat set of rules, but hundreds of them aggregated).</p>
<p>We will fit a random forest on the training data using the ranger engine (a fast implementation of random forests). We’ll specify, for example, 100 trees in the forest:</p>
<pre><code>library(ranger)
# Define a random forest model specification
rf_mod &lt;- rand_forest(trees = 100) %&gt;% 
  set_engine(&quot;ranger&quot;) %&gt;% 
  set_mode(&quot;regression&quot;)

# Fit the random forest on the training data
rf_fit &lt;- rf_mod %&gt;% fit(realinc ~ age + educ + sex, data = gss_train)</code></pre>
<pre><code># Performance on training data
rf_train_preds &lt;- predict(rf_fit, gss_train) %&gt;% bind_cols(gss_train)
rmse(rf_train_preds, truth = realinc, estimate = .pred, metrics = rmse)</code></pre>
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard      27192.</code></pre>
<pre><code># Performance on test data
rf_test_preds &lt;- predict(rf_fit, gss_test) %&gt;% bind_cols(gss_test)
rmse(rf_test_preds, truth = realinc, estimate = .pred, metrics = rmse)</code></pre>
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard      26977.</code></pre>
<p>Random forest did okay here but not excellent. Why? In other datasets with strong non-linear effects or interactions, a random forest would likely excel. Our example highlights that more complex models are not always better – it depends on the data and underlying patterns.</p>
<p>Again, we can rank predictors by importance.</p>
<pre><code>vip::vip(rf_fit$fit, num_features = 20) +
  ggtitle(&quot;Random forest – variable importance&quot;)</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="text-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="large-language-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yuzesui97/soc10_2025spring/edit/main/08-Machine_Learning.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/yuzesui97/soc10_2025spring/blob/main/08-Machine_Learning.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
